export const Events = {
  OBJECT_ADDED: 'objectAdded',
  OBJECT_REMOVED: 'objectRemoved',
  SELECTION_CHANGE: 'selectionChange',
  HISTORY_CHANGE: 'historyChange',
  LIGHT_ADDED: 'lightAdded',
  LIGHT_REMOVED: 'lightRemoved',
  LIGHT_UPDATED: 'lightUpdated',
  GROUP_ADDED: 'groupAdded',
  GROUP_REMOVED: 'groupRemoved',
  DELETE_OBJECT: 'deleteObject',
  SCENE_GRAPH_NEEDS_UPDATE: 'sceneGraphNeedsUpdate',
  UNDO: 'undo',
  REDO: 'redo',
  FOCUS_OBJECT: 'focus-object',
  UPDATE_GRID: 'update-grid',
  TOGGLE_AXES: 'toggle-axes',
  UI_UPDATE_PROPERTIES: 'ui-update-properties',
  HISTORY_CHANGED: 'history-changed',
  TOUCH_PINCH_START: 'touch-pinch-start',
  TOUCH_PINCH: 'touch-pinch',
  TOUCH_PAN: 'touch-pan',
  TOUCH_LONG_PRESS: 'touch-long-press'
};

export const ObjectTypes = {
  BOX: 'Box',
  SPHERE: 'Sphere',
  CYLINDER: 'Cylinder',
  CONE: 'Cone',
  TORUS: 'Torus',
  TORUS_KNOT: 'TorusKnot',
  TETRAHEDRON: 'Tetrahedron',
  ICOSAHEDRON: 'Icosahedron',
  DODECAHEDRON: 'Dodecahedron',
  OCTAHEDRON: 'Octahedron',
  PLANE: 'Plane',
  TUBE: 'Tube',
  TEAPOT: 'Teapot',
  LATHE: 'Lathe',
  EXTRUDE: 'Extrude',
  TEXT: 'Text',
  LOD_CUBE: 'LODCube',
};
